### ISSUE TITLE
The tool is not working on windows 10

### ISSUE THREAD

**Issue by MaggieWong27** [itead/Sonoff_Devices_DIY_Tools#14]
The tool is not working on windows 10. i get an error "failed to execute script pyi_rth_qt5plugins

**Comment by mattsaxon** [comment]
@maggiewong27, the tool works successfully on Windows 10 for me.

**Comment by geejayem99** [comment]
Also getting the same error.  win10 64bit

**Comment by mattsaxon** [comment]
What versions of python do you have installed?

**Comment by geejayem99** [comment]
None on this machine as far as I'm aware. Should I have?

**Comment by mattsaxon** [comment]
Yes you need Python installed. I have 3.7

**Comment by petarboj** [comment]
same error. python 3.7.4 installed.

**Comment by devtdr** [comment]
same issue here. windows 10 64 bit, python 3.7 .

**Comment by petarboj** [comment]
Well, on home PC, Win10 x64 without python - it works. Guys please try to install Visual C++ Redistributable for Visual Studio 2015,ć and try with it. I think I read this somewhere.

**Comment by devtdr** [comment]
> Well, on home PC, Win10 x64 without python - it works. Guys please try to install Visual C++ Redistributable for Visual Studio 2015, and try with it. I think I read this somewhere.

I have installed Visual C++ Redistributable .. 
When i hit Power On on the DIY Mode tool i get the following output. 
`performer_func {'ip': '192.168.137.128', 'port': '8081', 'switch': False, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -32}
发送数据： http://192.168.137.128:8081/zeroconf/switch {'deviceid': '1000958a91', 'data': {'switch': 'on'}}
正在发送 {"deviceid": "1000958a91", "data": {"switch": "on"}}
**lan_ewlink_api_error**`

**Comment by devtdr** [comment]
it work's for me now. The eWeLink app provided me the new Firmware 3.3 for the device. With the new Firmware I am able use the DIY Mode tool v3.3.0 .

**Comment by rlajos** [comment]
Also getting the same error (failed to execute script pyi_rth_qt5plugins). win10 64bit. Installed Python, no changes :/

**Comment by rediculum** [comment]
> it work's for me now. The eWeLink app provided me the new Firmware 3.3 for the device. With the new Firmware I am able use the DIY Mode tool v3.3.0 .

How can a mobile app fix a Windows Python executable?

**Comment by rediculum** [comment]
I have the same issue. I downloaded the log version and it gives me this error:

```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 47, in <module>
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 49, in <module>
  File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\PySide2\__init__.py", line 49, in <module>
  File "site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
  File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\shiboken2\__init__.py", line 4, in <module>
```
Pyton 3.7 installed and PyQt5 with pip. Visual C++ Redist also installed and rebooted. Nothing helps

**Comment by alexbk66** [comment]
For Python you need to set PYTHONPATH environment variable to point to your Python installation directory

**Comment by bobmoran00** [comment]
2 separate widow 10 PCs fresh installs of python 3.7.4 in the path and neither work.   Both fail with the "failed to execute script pyi_rth_qt5plugins" error.

**Comment by bobmoran00** [comment]
So:  Phone set as hotspot,  Win10 machine on hotspot wireless and has internet.  Mini at 3.3 on the same wireless.  The exe can't find tool_01DIY85.py so I run it manually "python tool_01DIY85.py" and I get the DIY Mode Tool,  it finds the mini,  I select it and attempt to flash and I get "Send unlock failed".  "Please check your network connection".  Even though it is connected to the same ssid and network the PC is.  Itead DIY is a fail.

**Comment by alexbk66** [comment]
I agree - Sonoff DIY is not production quality.  But it makes me wonder - does Itead have a plan to fix the problem? @ZZLinvec?

**Comment by Snipercaine** [comment]
I am pretty sure they are working on a better DIY solution, but I don't have any details.  
And just to be clear, ZZLinvec is not me :)

**Comment by alexbk66** [comment]
> And just to be clear, ZZLinvec is not me :)
I know, he used to reply, but now disappeared...

**Comment by bobmoran00** [comment]
OK this time the mini is moved successfully to a standard 2.4 wireless with internet and the tool is reconnected.  Attempting to flash still results in Send unlock Failed.  I am capturing packets during this on my wan firewall and the ip of the mini sends nothing.   It has a dhcp address and is pingable from the firewall and the lan.  On boot the mini only sends to a multicast IP 224.0.0.251:5353 udp. I have two minis both on ewlink 3.3 and they both do the same thing.  Any thoughts or do I put them in a drawer and wait for Itead to fix it?

**Comment by alexbk66** [comment]
Finally I managed to discover my devices!  After flashing FW 3.3 and disabling Ethernet adaptor on my laptop.

**Comment by ozmatox** [comment]
Hi, I had the same problem, I was installing Python, QT and other C + and every time I had this problem - suddenly it dawned on me to change the connection properties on my laptop's WiFi adapter to DHCP :) and everything started working fine!

WIFI -DHCP !!!!!!

**Comment by cataluca72** [comment]
Guys, I solved the problem!!!!!
after trying and trying I understood that it is something related to the PC, because if you change PC you can be lucky and find one that works. And I understood that depends also on the networking card, because some of you in this forum stated that.

And what I did?

I took a 10 euros wifi USB network card and magically my sonoff appeared!
I don't know what was blocking my PC. Maybe windows defender or maybe something else. But if with an inexpensive usb card I solve the problem, I stop wondering :)

Hope this post can help you!.
Luca

**Comment by alexpilotti** [comment]
In case anybody else has the "pyi_rth_qt5plugins" issue, you only need to install the MSVC redistributable x86 components (not x64): 
https://aka.ms/vs/16/release/vc_redist.x86.exe

There's no need to install Qt.

**Comment by flavius68** [comment]
Hi, I'm Flavio  i have a problem with tools 3.3.0, when install this version return: " failed to execute script tool_01DIY85.
I have installed  Python 3.9.7 e visula c++ 2015 also but tis tools Dyv not work. Thank's and Good Night

**Comment by DeanRos** [comment]
I have tried to run the diy tool but I get the error "This app cannot run on your pc" I have VS and Python loaded on my PC, is there any workaround?
