### ISSUE TITLE
Upload not starting

### ISSUE THREAD

**Issue by danyolgiax** [itead/Sonoff_Devices_DIY_Tools#22]
I'm using "tool_01DIY85(v3.3.0).exe" to flash a Sonoff Basic R3.

The device is listed and switches if I test ON/OFF.

When I try to flash it (after selecting the file and my device) the popup becomes gray but progress stuck at 0%.

In console I read:
...
100090cf4e >>> {'ip': '192.168.137.xx', 'port': '8081', 'switch': False, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -77}
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 367, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lan_ewlink_api.py", line 118, in run
  File "lan_ewlink_api.py", line 160, in performer_func
  File "lan_ewlink_api.py", line 392, in set_unlock
  File "lan_ewlink_api.py", line 170, in send_data
  File "lan_ewlink_api.py", line 44, in postRequest
  File "site-packages\requests\api.py", line 116, in post
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

what I miss?

**Comment by ZZLinvec** [comment]
Is the firmware version of Sonoff Basic R3 3.3.0?
If the firmware version is 3.1.0, the tool will not respond to 3.3.0.
So, your device should be version 3.3.0.
Again from the exception information, should be sent data is not quite right.
May I have a look at the data you sent?

**Comment by danyolgiax** [comment]
R3 Basic version is 3.3.0. 
I used a different WI-FI connection and magically it worked. 

I think the problem was a strange configuration of the first network.

Thanks anyway
