### ISSUE TITLE
"Failed to execute script tool_01DIY85" - windows 10

### ISSUE THREAD

**Issue by BlinkioAaron** [itead/Sonoff_Devices_DIY_Tools#40]
Hi, I have a fresh installation of Windows 10. I have tried all the methods suggested in this thread without success. This includes trying the run the python scripts directly, however this fails due to inconsistent spacing / tabs in the codebase and certain packages failing to install. When attempting to run the executable I get the following error "Failed to execute script tool_01DIY85". Are you able to look into this as I would like to use the DIY Mode as this was the reason for purchasing the Sonoff Mini's in the first place.

**Comment by edubox** [comment]
Same here

**Comment by GoBooth** [comment]
installed this, fixed my issue: https://www.qt.io/download  (the open source version)

I also installed python, but not 100% if it's needed

**Comment by jorgifumi** [comment]
> installed this, fixed my issue: https://www.qt.io/download (the open source version)
> 
> I also installed python, but not 100% if it's needed

This solution worked for me, without installing python. Thank you!

**Comment by Mateiuc** [comment]
Hi, which part of open source??..if its full install, its about 311 gb

> > installed this, fixed my issue: https://www.qt.io/download (the open source version)
> > I also installed python, but not 100% if it's needed
> 
> This solution worked for me, without installing python. Thank you!

Hi, which part (or module) of qt open source??..if its full install, it's about 311 gb...thanks!

**Comment by Mateiuc** [comment]
> > installed this, fixed my issue: https://www.qt.io/download (the open source version)
> > I also installed python, but not 100% if it's needed
> 
> This solution worked for me, without installing python. Thank you!

Hi, which part (or module) of qt open source??..if its full install, it's about 311 gb...thanks!

**Comment by BeringBullet** [comment]
C:\Sonoff\tool>"tool_01DIY85_v330(log).exe"
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 47, in <module>
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 49, in <module>
  File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\PySide2\__init__.py", line 49, in <module>
  File "site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
  File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\shiboken2\__init__.py", line 4, in <module>
ImportError: DLL load failed: The specified module


So I don't have a D drive

**Comment by Mateiuc** [comment]
> C:\Sonoff\tool>"tool_01DIY85_v330(log).exe"
> Traceback (most recent call last):
> File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 47, in
> ModuleNotFoundError: No module named 'PyQt5'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 49, in
> File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
> File "site-packages\PySide2__init__.py", line 49, in
> File "site-packages\PySide2__init__.py", line 21, in _setupQtDirectories File "D:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module File "site-packages\shiboken2__init__.py", line 4, in
> ImportError: DLL load failed: The specified module
> 
> So I don't have a D drive

Hi, try with DHCP, not fixed IP (for qt dll, i don't know about D drive).

**Comment by ramonsmits** [comment]
> installed this, fixed my issue: [qt.io/download](https://www.qt.io/download) (the open source version)
> 
> I also installed python, but not 100% if it's needed

@GoBooth What download is needed? I can only find downloads that require registration.

**Comment by ramonsmits** [comment]
I had to register and installing the default selected options with the web installer worked for me.

**Comment by frogale** [comment]
Same error after Qt install.. :-(

**Comment by ozmatox** [comment]
Hi, I had the same problem, I was installing Python, QT and other C + and every time I had this problem - suddenly it dawned on me to change the connection properties on my laptop's WiFi adapter to DHCP :) and everything started working fine!

WIFI -DHCP !!!!!!
