### ISSUE TITLE
Sonoff mini FW upgrade failed (sonoff_basic.bin). Progress bar always at 0%

### ISSUE THREAD

**Issue by Pask65** [itead/Sonoff_Devices_DIY_Tools#41]
Hi followed the procedure for upgrading my sonoff mini with the latest tasmota fw (sonoff_basic.bin v6.6.0). I have  win10 PC. I can see the device and switch on and off correctly using the tool tool_01DIY85(3.3.0).exe.
I started the firmware download procedure, selected the binasry file and sonoff device, clicked the OK button but the progress bar remains at 0%.
On the log file I see : 2019-09-01 21:24:51{"deviceid": "1000982e70", "data": {}}
I tried with the version tool_01DIY85_v330(log).exe
the log window shows:

_"....erformer_func {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
self.command_vrg== {'sha256sum': 'e2f84b9f469d3859d7962fc07fc93b9e6df6e3cec5b6b1c3492d1471b573269d', 'sever_ip': '192.168.43.166', 'sever_port': 776}
发送数据： http://192.168.43.176:8081/zeroconf/ota_unlock {'deviceid': '1000982e70', 'data': {}}
正在发送 {"deviceid": "1000982e70", "data": {}}
lan_ewlink_api_error
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
刷新 eWeLink_1000982e70._ewelink._tcp.local. 的信息 长度 397 ServiceInfo(type='_ewelink._tcp.local.', name='eWeLink_1000982e70._ewelink._tcp.local.', address=b'\xc0\xa8+\xb0', port=8081, weight=0, priority=0, server='eWeLink_1000982e70.local.', properties={b'txtvers': b'1', b'id': b'1000982e70', b'type': b'diy_plug', b'apivers': b'1', b'seq': b'15', b'data1': b'{"switch":"on","startup":"off","pulse":"off","sledOnline":"on","pulseWidth":500,"rssi":-20}'})
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 257, in _read_status
  File "socket.py", line 589, in readinto
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 367, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 257, in _read_status
  File "socket.py", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lan_ewlink_api.py", line 118, in run
  File "lan_ewlink_api.py", line 160, in performer_func
  File "lan_ewlink_api.py", line 392, in set_unlock
  File "lan_ewlink_api.py", line 170, in send_data
  File "lan_ewlink_api.py", line 44, in postRequest
  File "site-packages\requests\api.py", line 116, in post
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))
刷新 eWeLink_1000982e70._ewelink._tcp.local. 的信息 长度 397 ServiceInfo(type='_ewelink._tcp.local.', name='eWeLink_1000982e70._ewelink._tcp.local.', address=b'\xc0\xa8+\xb0', port=8081, weight=0, priority=0, server='eWeLink_1000982e70.local.', properties={b'txtvers': b'1', b'id': b'1000982e70', b'type': b'diy_plug', b'apivers': b'1', b'seq': b'15', b'data1': b'{"switch":"on","startup":"off","pulse":"off","sledOnline":"on","pulseWidth":500,"rssi":-20}'})
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}
刷新 eWeLink_1000982e70._ewelink._tcp.local. 的信息 长度 397 ServiceInfo(type='_ewelink._tcp.local.', name='eWeLink_1000982e70._ewelink._tcp.local.', address=b'\xc0\xa8+\xb0', port=8081, weight=0, priority=0, server='eWeLink_1000982e70.local.', properties={b'txtvers': b'1', b'id': b'1000982e70', b'type': b'diy_plug', b'apivers': b'1', b'seq': b'15', b'data1': b'{"switch":"on","startup":"off","pulse":"off","sledOnline":"on","pulseWidth":500,"rssi":-20}'})
1000982e70 >>> {'ip': '192.168.43.176', 'port': '8081', 'switch': True, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -20}_

Thanks

**Comment by rediculum** [comment]
Have you tried to set the SSID on the DIY tool for your ESP, wait some seconds, close DIY tool and open again? Your ESP should then be again visible, but this time over your own network and not the "sonoffDIY" hotspot. Try then to flash
Here's what Theo Arends also states:
```
If the firmware update gets stuck at 0%, the Sonoff device could not reach the manufacturer server because your mobile hotspot does not share the Internet connection. If this happens, use the DIY tool to set the SSID and password of your Wi-Fi network on the sonoff device. The device will connect to your network. Disable the hotspot and use your Wi-Fi for DIY tool laptop as well. Now start Brush machine again, flash Tasmota. Then continue with this guide.
```

**Comment by Pask65** [comment]
I tried to change the SSID but the result is the same :-(
The step sequence is : 
1. change the SSID  (my wifi AP)
2. close DIY tool
3.reopen the DIY tool
4.select sonoff_basic.bin
5. Push OK button

Thr progress bar remains at 0%

Following the relevant log data on the cmd window:

1000982e70 >>> {'ip': '192.168.1.30', 'port': '8081', 'switch': False, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -36}
刷新 eWeLink_1000982e70._ewelink._tcp.local. 的信息 长度 382 ServiceInfo(type='_ewelink._tcp.local.', name='eWeLink_1000982e70._ewelink._tcp.local.', address=b'\xc0\xa8\x01\x1e', port=8081, weight=0, priority=0, server='eWeLink_1000982e70.local.', properties={b'txtvers': b'1', b'id': b'1000982e70', b'type': b'diy_plug', b'apivers': b'1', b'seq': b'2', b'data1': b'{"switch":"off","startup":"off","pulse":"off","pulseWidth":500,"rssi":-36}'})
1000982e70 >>> {'ip': '192.168.1.30', 'port': '8081', 'switch': False, 'startup': 'off', 'pulse': False, 'pulseWidth': 500, 'rssi': -36}
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 367, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lan_ewlink_api.py", line 118, in run
  File "lan_ewlink_api.py", line 160, in performer_func
  File "lan_ewlink_api.py", line 392, in set_unlock
  File "lan_ewlink_api.py", line 170, in send_data
  File "lan_ewlink_api.py", line 44, in postRequest
  File "site-packages\requests\api.py", line 116, in post
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
刷新 eWeLink_1000982e70._ewelink._tcp.local. 的信息 长度 382 ServiceInfo(type='_ewelink._tcp.local.', name='eWeLink_1000982e70._ewelink._tcp.local.', address=b'\xc0\xa8\x01\x1e', port=8081, weight=0, priority=0, server='eWeLink_1000982e70.local.', properties={b'txtvers': b'1', b'id': b'1000982e70', b'type': b'diy_plug', b'apivers': b'1', b'seq': b'2', b'data1': b'{"switch":"off","startup":"off","pulse":"off","pulseWidth":500,"rssi":-36}'})
...

**Comment by Pask65** [comment]
I tried to **switch off and switch on  the sonoff mini** and now is working !!! :-)
It is mandatory to close the DIY tool and poweroff the Sonoff mini

Thanks for your suggestions

**Comment by dastrix80** [comment]
I also did this many many times, but ist still stuck.

**Comment by xiscopg** [comment]
I have tried all, but progress is always at 0%. could anyone help me?
thanks

**Comment by jmheist** [comment]
Stuck at 0% as well.

**Comment by xiscopg** [comment]
At end it has worked, I changed the ssid and password from tool DIY to my home ssid and password, so sonoff connect to my WiFi, my laptop connected by cable at same network, and so it worked for me.
I think probably that the problem is with w10 and its security, firewall o antivirus.

**Comment by jmheist** [comment]
@xiscopg was your laptop running something other than w10?

**Comment by xiscopg** [comment]
@jmheist I have Kaspersky installed but disabled and nothing else extra running. And I have tried with kaspersky uninstalled and it didn't work till I did what I wrote at the other post.

**Comment by jmheist** [comment]
Solved. My minis were on version 3.0.0 out of the box

1. Paired with phone app following compatibility mode.
2. Used phone app to update the each mini to 3.3.0
3. then put into DIY mode with jump
4. Added sonoffDiy wifi network
5. connected to the sonoff DIY tool on computer
6. turned off all firewalls on computer (windows 10 firewalls were the culprit)
7. Use sonoff tool to flash sonoff_basic.bin
8. followed tasmota setup procedures as normal.

**Comment by denisjoshua** [comment]
I also had the problem with tre progress bar that remained at 0. 
So I try the xiscopg  procedure and it's work. 

So using my android phone hotspot didn't work... have not see the sonoff in the tool.
Using the PC WiFi hot spot have see the sonoff and On/Off and the other think was worked, but progress bar didn't work. 

I changed the SSID and password using the tool with the SSID of my home network wifi. 
Run the tool another time and now was worked. 

I think this is some new Windows 10 compatibility issue. 
Hope this will help. 
Denis

**Comment by sameeraman** [comment]
Check the following:
1) Turn off Windows Firewall Temporarily
2) Disable all other Network adapters on the laptop. 
3) Run the DIY tool with Win 7 compatibility mood. 
![image](https://user-images.githubusercontent.com/18417281/72196985-65075580-3457-11ea-9d87-905e614ff80a.png)

These things did the trick for me.

**Comment by vsailo** [comment]
Please ensure that your Sonoff hotspot device has access to Internet. After my various attempts I could get working as soon as I switched on my Mobile (Sonoff hotspot device) data.

**Comment by nthewara** [comment]
I had the same issue and managed to resolve this by running "tool_01DIY85(3.3.0).exe" in Windows 7 compatibility mode.
